#(C) Copyright 2021 Hewlett Packard Enterprise Development LP

run:
  deadline: 240s
  tests: true
  skip-dirs:
    - vendor
  build-tags: acceptance

linters-settings:
  dupl:
    threshold: 110
  lll:
    line-length: 128
  goimports:
    local-prefixes: "github.com"
  godox:
    keywords:
      - OPTIMIZE
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 400
    statements: 60
  nestif:
    # minimal complexity of if statements to report
    min-complexity: 20
  goconst:
    ignore-tests: true

linters:
  enable-all: true
  disable:
    - gosec
    - dupl
    - wsl
    - gci
    - goerr113
    - godot
    - gomnd
    - gochecknoinits
    - gochecknoglobals
    - errcheck
    # - forbidigo
    - testpackage
    - nolintlint
    - scopelint
    - wrapcheck
    - nilerr
    - thelper
    # Temporarily disabling these
    - errorlint
    - predeclared
    - paralleltest
    - gocritic
    - forcetypeassert
    - ifshort
    - exhaustivestruct
    - cyclop
    - varnamelen
    - maintidx
    - ireturn
    #Temporarily disabling wrapcheck
    # - wrapcheck
    # Disable the 'cyclop' cyclometric complexity linter. 'gocyclo' already
    # covers cyclometric complexity, and 'cyclop' has no documentation to
    # help with resolving the flagged lints
    # - cyclop

issues:

  exclude-rules:
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

    # ignore function length for tests as look up tables typically exceed.
    - linters:
        - funlen
        - goerr113
      path: _test\.go

    # - linters:
    #     - dupl
    #   path: ".*generated.*go"

    - linters:
        - goconst
      path: ".*generated.*go"

    - linters:
        - staticcheck
      text: "SA9003:"

    - linters:
        - stylecheck
      text: "ST1005:"

  max-same-issues: 0
