vmaas:

  datasource:
    cloud:
      name: HPE GreenLake VMaaS Cloud

    datastore:
      cloud_id: 3
      name: Compute-Cluster-Vol0

    environment:
      name: Dev

    group:
      name: default

    layout:
      name: Vmware VM
      instance_type_code: vmware

    network_interface:
      name: E1000
      cloud_id: 3

    network:
      name: Blue-Net

    plan:
      name: G1-Small

    power_schedule:
      name: DEMO_WEEKDAY

    resource_pool:
      cloud_id: 3
      name: ComputeResourcePool

    template:
      name: vanilla-centos7-x86_64-09072020

# Resources
  resource:

    instance_clone:
      source_instance_id: 27129
      network:
        - id: 177
          interface_id: 0

    instance:
      name: tf_instance
      cloud_id: 3
      group_id: 6
      layout_id: 339
      plan_id: 1221
      instance_type_code: vmware
      network:
        - id: 117
          interface_id: 0
        - id: 117
          interface_id: 0
      volume:
        - name: root_vol
          datastore_id: 24
      scale: 2
      config:
        resource_pool_id: 6
        no_agent: true
        template_id: 1719
