# (c) Copyright 2021 Hewlett Packard Enterprise Development LP
version: 2.1

defaults: &defaults
  docker:
    - image: 657273346644.dkr.ecr.us-east-1.amazonaws.com/hpe-hcss/go-build:v0.1.5
      environment:
        GO111MODULE: "on"

common-context: &common-context
  context: ecr-6644

common-filters: &filters
  filters:
    tags:
      only: /.*/

common-settings: &common
  <<: [*common-context, *filters]

restore_cache:  &restore_cache
  restore_cache:
    key: gopkg-v1-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}

workflows:
  secret-scanning:
    jobs:
      - secret-scanning:
          # for AWS creds to download image
          <<: *common-context

  build_terraform:
    jobs:
      - checkout-workspace:
          <<: *filters
      - copyright-check:
          <<: *common
          requires:
            - checkout-workspace
      - go-vendor:
          <<: *common
          requires:
            - copyright-check
      - go-lint:
          <<: *common
          requires:
            - go-vendor
      - go-build:
          <<: *common
          requires:
            - go-lint

  acceptance:
    jobs:
      - acceptance-run:
          <<: *filters
          # filters:
          #   branches:
          #     only: master

jobs:
  secret-scanning:
    docker:
      - image: 657273346644.dkr.ecr.us-east-1.amazonaws.com/hpe-hcss/secrets-scanner:v0.3.3
    working_directory: /src
    steps:
      # also injects host key
      - checkout
      - run:
          name: Check for secrets leaked
          command: scanner

  checkout-workspace:
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths: ['.']

  copyright-check:
    docker:
      - image: 657273346644.dkr.ecr.us-east-1.amazonaws.com/hpe-hcss/copyright-tool:0.3.0
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Check copyright
          command: |
            copyright-tool --check

  go-vendor:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: go-vendor
          command: |
            git config --global url.https://$GITHUB_TOKEN@github.com/.insteadOf https://github.com/
            make vendor
      - persist_to_workspace:
          root: ~/project
          paths:
            - vendor
            - go.mod
            - go.sum
      - save_cache:
          key: gopkg-v1-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg

  go-lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - <<: *restore_cache
      - run:
          name: go-lint
          command: |
            make lint

  go-build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - <<: *restore_cache
      - run:
          name: go-build
          command: |
            make build

  acceptance-run:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths: ['.']
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y wget jq
            wget https://golang.org/dl/go1.16.5.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo tar -C /usr/local -xzf go1.16.5.linux-amd64.tar.gz
            echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc

            wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
            sudo unzip terraform_1.0.0_linux_amd64.zip -d /usr/local/bin

      - run:
          name: Set environment values
          command:
            |
            export HPEGL_IAM_TOKEN=`curl --location -g --request POST "${CMP_SUBJECT}/oauth/token?grant_type=password&scope=write&client_id=morph-customer" \
            --header 'Content-Type: application/x-www-form-urlencoded' \
            --data-urlencode "username=${CMP_USERNAME}" \
            --data-urlencode "password=${CMP_PASSWORD}" | jq -r ."access_token"`

      - attach_workspace:
          at: ~/project
      - run:
          name: go-vendor
          command: |
            git config --global url.https://$GITHUB_TOKEN@github.com/.insteadOf https://github.com/
            make vendor
      - persist_to_workspace:
          root: ~/project
          paths:
            - vendor
            - go.mod
            - go.sum
      - save_cache:
          key: gopkg-v1-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg
      - run:
          name: Run acceptance test
          command:
            make acceptance
