data-sources:
acc:
- config: |
    name = "HPE GreenLake VMaaS Cloud"
acc:
- config: |
    name     = "ComputeFolder"
    cloud_id = 3
  validations:
    json.folder.id: 3
    tf.code: "group-v220"acc:
- config: |
    name = "Compute-Cluster-Vol0"
    cloud_id = 3
acc:
- config: |
    name     = "dev"
acc:
- config: |
    name     = "default"
acc:
- config: |
    name               = "Vmware VM"
    instance_type_code = "vmware"
acc:
- config: |
    name = "Blue-Net"
acc:
- config: |
    name     = "E1000"
    cloud_id = 3
acc:
- config: |
    name = "G1-Small"
acc:
- config: |
    name = "DEMO_WEEKDAY"
acc:
- config: |
    name = "ComputeResourcePool"
    cloud_id = 3
acc:
- config: |
    name = "vanilla-centos7-x86_64-09072020"
resources:
acc:
- config: |
    name = "tf_instance"
    cloud_id = 3
    group_id = 6
    layout_id = 339
    plan_id = 1221
    instance_type_code = "vmware"
    network {
        id = 117
        interface_id = 0
    }
    volume {
        name = "root_vol"
        datastore_id = 24
        size = 5
      }
    scale = 2
    config {
      resource_pool_id = 6
      no_agent = true
      template_id = 1719
      folder_code = "group-v220"
    }
  validations:
    tf.status: "running"
acc:
- config: |
    source_instance_id = 27129
    name = "tf_acc_clone_%rand_int"
    network {
      id           = 177
      interface_id = 0
    }
