name: Dev Acceptance Tests for CI CD

on:
  workflow_dispatch:

jobs:
  test-provider:
    uses: ./.github/workflows/reusable-dev-acc.yml
    with:
      test_case: TestProvider
    secrets: inherit

  test-datasouces:
    needs: 
      - test-provider
    if: "${{ needs.test-provider.result == 'success' }}"
    uses: ./.github/workflows/reusable-dev-acc.yml
    with:
      test_case: TestAccDataSource
    secrets: inherit

  test-vmaas-instance:
    uses: ./.github/workflows/reusable-dev-acc.yml
    needs: 
      - test-datasouces
    if: always()
    with:
      test_case: TestVmaasInstance
    secrets: inherit

  test-vmaas-resource-instance:
    uses: ./.github/workflows/reusable-dev-acc.yml
    needs: 
      - test-vmaas-instance
    if: always()
    with:
      test_case: TestAccResourceInstance
    secrets: inherit 

  test-vmaas-lb:
    uses: ./.github/workflows/reusable-dev-acc.yml
    needs: 
      - test-vmaas-resource-instance
    if: always()
    with:
      test_case: TestVmaasLB
    secrets: inherit

  test-vmaas-resource-lb:
    uses: ./.github/workflows/reusable-dev-acc.yml
    needs: 
      - test-vmaas-lb
    if: always()
    with:
      test_case: TestAccResourceLB
    secrets: inherit

  test-vmaas-lb-plan:
    uses: ./.github/workflows/reusable-dev-acc.yml
    needs: 
      - test-vmaas-resource-lb
    if: always()
    with:
      test_case: "TestVmaasLoadBalancerPlan TestAccResourceLoadBalancerCreate"
    secrets: inherit
