name: Dev Acceptance Tests

on:
  # Runs every 2 days once at 3AM
  # schedule:
  #   - cron:  '0 21 */2 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        test_case:
          description: 'Enter testcase'     
          required: false
          default: ''
          type: string

  # release:
  #   types: [published]
env:
  HPEGL_IAM_SERVICE_URL: ${{ secrets.DEV_HPEGL_IAM_SERVICE_URL }}
  HPEGL_TENANT_ID: ${{ secrets.DEV_HPEGL_TENANT_ID }}
  HPEGL_USER_SECRET: ${{ secrets.DEV_HPEGL_USER_SECRET }}
  HPEGL_USER_ID: ${{ secrets.DEV_HPEGL_USER_ID }}
  HPEGL_VMAAS_API_URL: ${{ secrets.DEV_HPEGL_VMAAS_API_URL }}
  HPEGL_VMAAS_LOCATION: ${{ secrets.DEV_HPEGL_VMAAS_LOCATION }}
  HPEGL_VMAAS_SPACE_NAME: ${{ secrets.DEV_HPEGL_VMAAS_SPACE_NAME}}
  TF_ACC: ${{ secrets.TF_ACC }}
  LOG_FILE: "${{ github.event.inputs.test_case }}Logs.txt"
jobs:
  acc:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.17' ]
    name: Dev Acceptance Tests
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Install dependencies
        run: |
          sudo apt-get install -y wget jq
          wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
          sudo unzip -fo terraform_1.0.0_linux_amd64.zip -d /usr/local/bin

      - name: Install necessary tools
        run: make tools

      - name: Run Acceptance test
        run: |
          echo "Run date and time: $(date +'%Y-%m-%dT%H:%M:%S')" >> $LOG_FILE
          export TF_ACC_TEST_PATH="$(pwd)/acc-dev-testcases" && make acceptance case='${{ github.event.inputs.test_case }}' >> $LOG_FILE
      
      - name: Print testcases output
        run: cat $LOG_FILE
  
      - name: Push the report to github artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "Terraform Test report ${{ github.event.inputs.test_case }}"
          path: ${{ env.LOG_FILE }}
