name: Dev Acceptance Testing
# This workflow is intended to run a particular set of testcases
# If want to execute all test, consider running cicd-dev-acc.yml

on:
  # Runs every 2 days once at 3AM
  # schedule:
  #   - cron:  '0 21 */2 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        test_case:
          description: 'Enter testcases sperated by space'     
          required: true
          default: 'TestProvider'
          type: string
        test_description:
          description: 'Enter description for the test'     
          required: true
          default: 'Check Terraform Dev Testcase'
          type: string

jobs:
  acc-test:
    uses: ./.github/workflows/reusable-dev-acc.yml
    with:
      test_case: ${{ inputs.test_case }}
      test_description: ${{ inputs.test_description }}
    secrets:
      DEV_HPEGL_IAM_SERVICE_URL: ${{ secrets.DEV_HPEGL_IAM_SERVICE_URL }}
      DEV_HPEGL_TENANT_ID: ${{ secrets.DEV_HPEGL_TENANT_ID }}
      DEV_HPEGL_USER_SECRET: ${{ secrets.DEV_HPEGL_USER_SECRET }}
      DEV_HPEGL_USER_ID: ${{ secrets.DEV_HPEGL_USER_ID }}
      DEV_HPEGL_VMAAS_API_URL: ${{ secrets.DEV_HPEGL_VMAAS_API_URL }}
      DEV_HPEGL_VMAAS_LOCATION: ${{ secrets.DEV_HPEGL_VMAAS_LOCATION }}
      DEV_HPEGL_VMAAS_SPACE_NAME: ${{ secrets.DEV_HPEGL_VMAAS_SPACE_NAME}}
      TF_ACC: ${{ secrets.TF_ACC }}
