name: Dev Acceptance Tests

on:
  # Runs every 2 days once at 3AM
  # schedule:
  #   - cron:  '0 21 */2 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test scenario tags'
  # release:
  #   types: [published]
env:
  HPEGL_IAM_SERVICE_URL: ${{ secrets.DEV_HPEGL_IAM_SERVICE_URL }}
  HPEGL_TENANT_ID: ${{ secrets.DEV_HPEGL_TENANT_ID }}
  HPEGL_USER_SECRET: ${{ secrets.DEV_HPEGL_USER_SECRET }}
  HPEGL_USER_ID: ${{ secrets.DEV_HPEGL_USER_ID }}
  HPEGL_VMAAS_API_URL: ${{ secrets.DEV_HPEGL_VMAAS_API_URL }}
  HPEGL_VMAAS_LOCATION: ${{ secrets.DEV_HPEGL_VMAAS_LOCATION }}
  HPEGL_VMAAS_SPACE_NAME: ${{ secrets.DEV_HPEGL_VMAAS_SPACE_NAME}}
  TF_ACC: ${{ secrets.TF_ACC }}
jobs:
  acc:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.17' ]
    name: Dev Acceptance Tests
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: Install dependencies
        run: |
          sudo apt-get install -y wget jq
          wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
          sudo unzip -fo terraform_1.0.0_linux_amd64.zip -d /usr/local/bin

      - name: Install necessary tools
        run: make tools

      - name: Run Acceptance test
        run: |
          TF_ACC_TEST_PATH="$(pwd)/acc-dev-testcases" && make acceptance